version: '3'
services:
  nginx:
    image: nginx:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "7001:80"
      - "7002:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www/html
      - ./logs:/var/log/nginx
    links:
      - php
      - mysql
    networks:
      - backend
      - fronend
  php:
    build: ./images/php
    depends_on:
      - mysql
    volumes:
      - ./www:/var/www/html
    networks:
      - backend
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "7003:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db
    networks:
      - backend
networks:
  backend: ~
  fronend: ~